import Link from "next/link";

const foundations = [
  { number: "00", title: "What is a computer?", objective: "Notice how instructions, memory and inputs turn ideas into actions.", activity: "Teach a paper machine one precise instruction.", project: "A tiny instruction system for something you already know." },
  { number: "01", title: "What is data?", objective: "See data as observations with context, not just numbers on a screen.", activity: "Label a small set of everyday objects and question your labels.", project: "A data story that shows what was included—and what was missed." },
  { number: "02", title: "Algorithms & instructions", objective: "Break a task into steps, test them, and improve the sequence.", activity: "Write two routes to the same outcome and compare them.", project: "A reusable recipe a friend can follow without guessing." },
  { number: "03", title: "What is AI?", objective: "Build a clear mental model of systems that find patterns in examples.", activity: "Sort examples by rules, then notice where the rules break.", project: "A visual explanation of one AI system in your world." },
  { number: "04", title: "Machine learning by example", objective: "Understand training examples, patterns, predictions and uncertainty.", activity: "Change the examples and observe how the prediction changes.", project: "A labelled experiment log with a claim and evidence." },
  { number: "05", title: "Classification & patterns", objective: "Explore categories, boundaries, edge cases and better questions.", activity: "Design a fair sorting game and test it with a partner.", project: "A pattern classifier with a documented failure case." },
];

export default function LearningPage() {
  return <main className="learning-page">
    <header className="learning-header shell"><Link href="/" className="back-link">← Bhavya Foundation</Link><span className="learning-status">A proposed learning architecture</span></header>
    <section className="learning-hero shell"><div><p className="eyebrow">Free AI learning / the foundation path</p><h1>Build the <em>ground</em> before you build the future.</h1><p>AI changes quickly. Curiosity, computing, evidence and care last longer. This proposed path is designed to help a learner move from first principles to meaningful projects—one understandable step at a time.</p></div><div className="learning-seal" aria-hidden="true"><span>Learn</span><b>→</b><span>Try</span><b>→</b><span>Build</span><b>→</b><span>Reflect</span></div></section>
    <section className="learning-path shell" aria-labelledby="path-title"><div className="learning-section-head"><div><p className="eyebrow">A map, not a race</p><h2 id="path-title">Start with the foundations.</h2></div><p>Every module should leave a learner with a clearer idea, a small experiment, and something they can explain to someone else.</p></div><div className="path-levels" aria-label="Proposed progression"><span className="active">Foundation</span><span>Beginner</span><span>Intermediate</span><span>Advanced</span><span>Expert</span></div><div className="module-grid">{foundations.map((module)=><article className="module-card" key={module.number}><div className="module-top"><span>Module {module.number}</span><span className="module-dot" aria-hidden="true" /></div><h3>{module.title}</h3><p className="module-objective">{module.objective}</p><div className="module-steps"><span><b>Try</b>{module.activity}</span><span><b>Build</b>{module.project}</span></div><span className="proposed-tag">Proposed · Foundation review required</span></article>)}</div></section>
    <section className="learning-principles shell" aria-labelledby="principles-title"><div><p className="eyebrow">How learning feels</p><h2 id="principles-title">Understand enough to make a move.</h2></div><div className="principle-list"><div><span>01</span><strong>Make it visible</strong><p>Use examples, diagrams and small experiments to turn an abstract idea into something observable.</p></div><div><span>02</span><strong>Make it yours</strong><p>Keep a project trail: what you tried, what changed, what surprised you and what you would test next.</p></div><div><span>03</span><strong>Make it safe</strong><p>Future sharing and mentorship must be reviewed, moderated and designed for young learners.</p></div></div></section>
    <section className="learning-resources shell" aria-labelledby="resources-title"><div><p className="eyebrow">Open doors, careful provenance</p><h2 id="resources-title">Learn from the wider field.</h2><p>Some resources are free to access. Fewer are free to adapt. The resource map records that difference so Bhavya can link, attribute, adapt, or create original material deliberately.</p><Link className="button" href="/knowledge">Open the knowledge space ↗</Link></div><div className="resource-note"><span>Resource map</span><strong>Free ≠ open ≠ ours</strong><p>Every external source needs a license check before it becomes part of an official lesson.</p><Link href="/knowledge">Read the principle →</Link></div></section>
    <footer className="footer shell"><Link className="footer-brand" href="/"><span>Bhavya Foundation</span></Link><p>Proposed architecture, not published curriculum.</p><small>Review before release.</small></footer>
  </main>;
}
