import Image from "next/image";
import Link from "next/link";
const missions = [
  ["Forest","Restoring ecosystems and caring for the living systems that sustain us.","/missions#forest"],
  ["Knowledge","Expanding learning, research and responsible access to knowledge.","/missions#knowledge"],
  ["Heritage","Preserving the wisdom, places and practices carried across generations.","/missions#heritage"],
  ["Community","Empowering communities through thoughtful, lasting institutions.","/missions#community"]
];
export default function HomePage() { return <main>
  <header className="site-header shell"><Link className="brand" href="/" aria-label="Bhavya Foundation home"><Image src="/logo.png" alt="Bhavya Foundation" width={152} height={132} priority /></Link><nav aria-label="Primary navigation"><Link href="/about">About</Link><Link href="/missions">Missions</Link><Link href="/learning">Learn AI</Link><Link href="/labs">AI Labs</Link></nav><Link className="button small" href="/learning">Explore learning ↗</Link></header>
  <section className="hero shell" aria-labelledby="hero-title"><div className="hero-copy"><p className="eyebrow">An institution for generations</p><h1 id="hero-title">Building for <em>generations.</em></h1><p className="hero-lede">Restoring nature. Advancing knowledge. Preserving heritage. Empowering communities.</p><div className="actions"><Link className="button" href="/about">Discover Bhavya ↗</Link><Link className="text-link" href="/missions">Our missions →</Link></div></div><div className="hero-art" aria-hidden="true"><div className="sun"/><div className="mountain back"/><div className="mountain front"/><div className="hero-tree"/></div></section>
  <section className="section shell" aria-labelledby="mission-title"><div className="section-heading"><div><p className="eyebrow">Our permanent missions</p><h2 id="mission-title">Four ways to build a shared tomorrow.</h2></div><p>Bhavya works across enduring areas of responsibility for people and the planet.</p></div><div className="mission-grid">{missions.map(([title,text,href])=><Link className="mission-card" href={href} key={title}><span className="card-mark" aria-hidden="true">✦</span><h3>{title}</h3><p>{text}</p><span className="card-link">Explore ↗</span></Link>)}</div></section>
  <section className="learning-callout shell" aria-labelledby="learning-title"><div><p className="eyebrow">A learning ecosystem</p><h2 id="learning-title">Make the distance between curiosity and capability smaller.</h2><p>Bhavya is building a free AI learning pathway for students, including learners who may not have a computer at home. Online learning and future physical AI Labs will work together over time.</p><Link className="button light" href="/learning">Explore AI learning ↗</Link></div><div className="learning-orbit" aria-hidden="true"><span>Learn</span><span>Practice</span><span>Build</span><span>Share</span></div></section>
  <section className="section shell onward" aria-labelledby="onward-title"><p className="eyebrow">Start where you are</p><h2 id="onward-title">Explore the Bhavya ecosystem.</h2><div className="link-grid"><Link href="/learning"><strong>AI learning</strong><span>Free learning pathways and practical experimentation. <b>↗</b></span></Link><Link href="/labs"><strong>AI Labs</strong><span>Learn about the physical access model under development. <b>↗</b></span></Link><Link href="/knowledge"><strong>Knowledge</strong><span>A growing home for responsible learning and institutional knowledge. <b>↗</b></span></Link></div></section>
  <footer className="footer shell"><Link className="footer-brand" href="/"><Image src="/logo.png" alt="Bhavya Foundation" width={105} height={91}/><span>Nature. Knowledge. Heritage.</span></Link><p>Building institutions that strengthen nature, knowledge and heritage.</p><small>© {new Date().getFullYear()} Bhavya Foundation</small></footer>
</main>; }
